### ISSUE TITLE
Pages on HTTPS aren't fully secure because it's loading thumbnails from HTTP

### ISSUE THREAD

**Issue by blha303** [BenjaminAdams/RedditJS#59]
e.g. https://redditjs.com/r/AutoModerator The thumbnail at the top left makes the page insecure. Reddit has https for the whole site now, changing links to https when using redditjs securely would be an easy change (and one that I'd make and PR, but I can't find where that change should go :P)

**Comment by dotser02** [comment]
It appears that Reddit is not fixing this. Any suggestions for how to fix this? Warnings still blow up the console when using redditjs.com

**Comment by BenjaminAdams** [comment]
Could always do a string replace http for https in the thumbnail url.
Would also have to do it for css assets.  Even if you did all of that, the
content posted images would all need to be https capable (hint: they are
not)

**Comment by dotser02** [comment]
Ah, I see now. Thank you for the quick response. 

Also thank you for creating Redditjs. I am currently incorporating it into my senior project. Other than the warnings (which aren't really even on your end) Redditjs works very smoothly and nicely with everything we are doing.

**Comment by BenjaminAdams** [comment]
Glad to hear you have enjoyed!

What are you doing for your senior project? (curious...)

**Comment by dotser02** [comment]
We're attempting to build an "all in one" website. A site you can go to, and have reddit, Facebook, your choice of music website, twitter, etc., all open on the same page.

one4all.me

That will give you an idea, but many of the things will not work unless you are on our developer list. (Facebook and Twitter applications require some hoop jumping until we establish that our application is finished and we are live)

**Comment by BenjaminAdams** [comment]
Neat idea!  let me know when it goes live =)

**Comment by dotser02** [comment]
Will do!
