### ISSUE TITLE
Respect user's preferences to disallow robots on profiles

### ISSUE THREAD

**Issue by lightswitch05** [BenjaminAdams/RedditJS#60]
Reddit allows users to choose if they want robots to index their profile pages or not. Recently this preference was not available to non-authenticated APIs, but a [recent change](https://github.com/reddit/reddit/pull/1164) has made this preference easily accessible via the `/u/:username/about.json` API.

I looked through the code to see about implementing this feature request, but I have little experience with backbone and marionette. I was thinking an easy implementation would be putting

```
 meta(name='robots', content='index, follow')
```

in the `index.jade` template. Then having a setter in user-view.js

```
allowRobots: function(allow) {
    if(allow === true){
        this.$('meta[name=robots]').attr('content', 'index, follow');
    } else {
        this.$('meta[name=robots]').attr('content', 'noindex, nofollow');
    }
}
```

then calling the setter from render or somewhere. Thoughts?

**Comment by lightswitch05** [comment]
@BenjaminAdams my profile has finally disappeared from Google's index. This is a great feature and I'm very thankful that you've implemented it!

**Comment by BenjaminAdams** [comment]
Hey that's great guy!
