### ISSUE TITLE
Commenting on history

### ISSUE THREAD

**Issue by umeboshi2** [BenjaminAdams/RedditJS#65]
RedditJS doesn't seem to be able to distinguish between articles/threads where commenting is permissible and when the article/thread is archived and no longer writable.

BTW, thanks for making this!  I've been using marionette and have been pleased with how it works.  This app is pretty nifty!

**Comment by BenjaminAdams** [comment]
When does reddit disable comments on a post?  After one year?

There is no property in the API that indicates comments are disabled.

Here's an example post over a year old and its disabled http://www.reddit.com/r/AskReddit/comments/12ly88/is_there_anything_that_truly_annoys_you_but.json

**Comment by BenjaminAdams** [comment]
It's live now

You can see comments disabled on this old post https://redditjs.com/r/AskReddit/comments/12ly88/is_there_anything_that_truly_annoys_you_but

**Comment by umeboshi2** [comment]
You are cool!  Funny thread.  It would be nice if they had an "archived" or such property.  Thanks!
