### ISSUE TITLE
The Post.js no longer works

### ISSUE THREAD

**Issue by RockyKev** [BenjaminAdams/RedditJS#71]
Thank you for creating this plug-in.

redditjs.com/post.js

Via your page - it doesn't show the example. I tested it on my site as well no deal. 
Any assistance would great!

**Comment by BenjaminAdams** [comment]
Can you try using http://js4.red/post.js reddit made me change domain names

**Comment by RockyKev** [comment]
Holy moley! Thanks for the incredibly quick response!
You're amazing!

I replaced the URL with http://js4.red/post.js instead. Unfortunately,
nothing is showing.

Screenshots: http://i.imgur.com/F67F5ft.png

On this page: http://embed.redditjs.com/
The post examples don't show up as well, but the examples for the sidebar
do.





Thank you so much! :)

*-Rocky*

Find me on:
<http://t.sidekickopen42.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8rBpvgVdVn2264kcpnW7fsFDW56dLlLf6D8D0d02?t=https%3A%2F%2Fplus.google.com%2Fu%2F0%2F%2BRockyKev&si=5770801365647360&pi=a5bb052d-5cd8-454e-acc7-90c3eeffc814>

<http://t.sidekickopen42.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8rBpvgVdVn2264kcpnW7fsFDW56dLlLf6D8D0d02?t=https%3A%2F%2Fwww.linkedin.com%2Fin%2Frockykev&si=5770801365647360&pi=a5bb052d-5cd8-454e-acc7-90c3eeffc814>

<http://t.sidekickopen42.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8rBpvgVdVn2264kcpnW7fsFDW56dLlLf6D8D0d02?t=https%3A%2F%2Ftwitter.com%2Frockykev&si=5770801365647360&pi=a5bb052d-5cd8-454e-acc7-90c3eeffc814>


The Old Man, the Child, and the Donkey
<http://t.sidekickopen42.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8rBpvgVdVn2264kcpnW7fsFDW56dLlLf6D8D0d02?t=https%3A%2F%2Fplus.google.com%2F110563242018426632956%2Fposts%2FNSiGDFpZXpR&si=5770801365647360&pi=a5bb052d-5cd8-454e-acc7-90c3eeffc814>

or why you shouldn't try to please everyone.

**Comment by BenjaminAdams** [comment]
Its working for me...

If you visit https://js4.red/post.js in your browser does it show source code?

Also in your screenshot you are using http, try using https

**Comment by BenjaminAdams** [comment]
If you refresh your browser cache it should work now.

<script src='https://js4.red/post.js' data-url='48xak5'></script>

**Comment by RockyKev** [comment]
Hi benjamin!

I apologize for the late response.
Weird - it works on and off. Which tells me, you're code is working
correctly!
Something is up on my end, which I'll figure out.

Thank you so much for the quick responses. I really apprecaite it!


Thank you so much! :)

*-Rocky*

Find me on:
<http://t.sidekickopen45.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8rBpvgVdVn2264kcpnW7fsFDW56dLlLf6D8D0d02?t=https%3A%2F%2Fplus.google.com%2Fu%2F0%2F%2BRockyKev&si=5770801365647360&pi=1ba612f1-7b86-4adf-cb99-c70e0bf1908e>

<http://t.sidekickopen45.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8rBpvgVdVn2264kcpnW7fsFDW56dLlLf6D8D0d02?t=https%3A%2F%2Fwww.linkedin.com%2Fin%2Frockykev&si=5770801365647360&pi=1ba612f1-7b86-4adf-cb99-c70e0bf1908e>

<http://t.sidekickopen45.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8rBpvgVdVn2264kcpnW7fsFDW56dLlLf6D8D0d02?t=https%3A%2F%2Ftwitter.com%2Frockykev&si=5770801365647360&pi=1ba612f1-7b86-4adf-cb99-c70e0bf1908e>


The Old Man, the Child, and the Donkey
<http://t.sidekickopen45.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8rBpvgVdVn2264kcpnW7fsFDW56dLlLf6D8D0d02?t=https%3A%2F%2Fplus.google.com%2F110563242018426632956%2Fposts%2FNSiGDFpZXpR&si=5770801365647360&pi=1ba612f1-7b86-4adf-cb99-c70e0bf1908e>

or why you shouldn't try to please everyone.
